FROM python:3.11.4-bullseye

LABEL key="ml-team"

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY . /app

WORKDIR /app

COPY requirements.txt /app

RUN python3 -m pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["python", "app.py"]